# Generated by Django 5.2 on 2025-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(db_column='CI', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_reg', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_ing', models.DateField(blank=True, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_c', models.CharField(max_length=1)),
                ('tipo_e', models.CharField(max_length=1)),
                ('es_admin', models.CharField(max_length=1)),
            ],
        ),
    ]
