# Generated by Django 5.2 on 2025-05-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionarAdministracion', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
