# Generated by Django 5.2 on 2025-05-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionarAdministracion', '0006_delete_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(db_column='CI', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_reg', models.DateField(blank=True, null=True)),
                ('fecha_ing', models.DateField(blank=True, null=True)),
                ('tipo_c', models.CharField(max_length=1)),
                ('tipo_e', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
